export const demoLeads = [
  {
    id: "demo-maya-chen",
    name: "Maya Chen",
    company: "Northstar Studio",
    email: "maya@example.com",
    event: "Summit for Good 2026",
    notes: "Asked about hosting a partner reception for 80 guests in November. Interested in the garden space and requested a sample menu.",
    follow_up_status: "Follow-up due",
    created_at: "2026-09-18T10:00:00.000Z",
  },
  {
    id: "demo-noah-williams",
    name: "Noah Williams",
    company: "Brightline Labs",
    email: "noah@example.com",
    event: "Future of Work Expo",
    notes: "Exploring venues for the annual customer meetup. Needs hybrid AV and a breakout room. Checking dates with the team this week.",
    follow_up_status: "Qualified",
    created_at: "2026-09-15T10:00:00.000Z",
  },
  {
    id: "demo-priya-shah",
    name: "Priya Shah",
    company: "Common Ground",
    email: "priya@example.com",
    event: "Creative Cities Forum",
    notes: "Met at the welcome reception. Requested the accessibility guide and a capacity breakdown for the main hall.",
    follow_up_status: "Contacted",
    created_at: "2026-09-12T10:00:00.000Z",
  },
  {
    id: "demo-ethan-brooks",
    name: "Ethan Brooks",
    company: "Fieldwork Collective",
    email: "ethan@example.com",
    event: "Gathering Places Conference",
    notes: "Interested in a small team offsite next spring. No date selected yet; send the overview when available.",
    follow_up_status: "New",
    created_at: "2026-09-08T10:00:00.000Z",
  },
];

